language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src/llevame
script:
  - pytest --cov .
after_success:
  - coveralls
