language: python
services:
  - mongodb
python:
  - 3.5
install:
  - pip install -r requirements.txt
before_script:
  - export MONGO_URI=127.0.0.1
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src/llevame
  # Esta no se usa, pero se necesita igual.
  - export SHARED_SERVER_ADDR=http://shared-server:4000
script:
  - pytest --cov .
after_success:
  - coveralls
