version: "3"
services:

  mdb:
    build:
      context: mdb
    ports:
      - "27017:27017"

  app-server:
    build:
      context: .
      args:
        HTTP_PROXY: "$HTTP_PROXY"
        HTTPS_PROXY: "$HTTPS_PROXY"
    image: as
    environment:
      - PROD=$PROD
      - PORT=$PORT
      - DATABASE_URL=$DATABASE_URL
    ports:
      - "$PORT:3000"
    depends_on:
      - mdb
    environment:
    - MONGO_URI=mdb

networks:
  default:
    external:
      name: ubernet
