version: "3"
services:
  mdb:
    build:
      context: mdb
    ports:
      - "27017:27017"

  app-server:
    build:
      context: .
      args:
        HTTP_PROXY: "$HTTP_PROXY"
        HTTPS_PROXY: "$HTTPS_PROXY"
    image: as
    environment:
      - PROD=$PROD
      - PORT=$PORT
      - DATABASE_URL=$DATABASE_URL
    ports:
      - "3000:$PORT"
    depends_on:
      - mdb
