version: "3"
services:
  app-server:
    build:
      context: .
      args:
        HTTP_PROXY: "$HTTP_PROXY"
        HTTPS_PROXY: "$HTTPS_PROXY"
    image: ss
    environment:
      - PROD=$PROD
      - PORT=$PORT
      - DATABASE_URL=$DATABASE_URL
    ports:
      - "3000:$PORT"
